@extends('dashboard.layouts.app')
@section('content')
    <div class="content-wrapper">
        <div class="container-xxl flex-grow-1 container-p-y">
            <div class="row gy-6">
                <div class="card">
                    <div class="card-header d-flex justify-content-between align-items-center">
                        <h5 class="mb-0">Bookings Management</h5>
                        <div class="card-header-elements">
                            <input type="text" id="searchInput" class="form-control" placeholder="Search hikers..."
                                style="width: 250px;">
                        </div>
                    </div>
                    <div class="table-responsive text-nowrap">
                        <table class="table" id="bookingsTable">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Pendaki</th>
                                    <th>Email</th>
                                    <th>Gunung</th>
                                    <th>Team</th>
                                    <th>Check-in</th>
                                    <th>Check-out</th>
                                    <th>Status</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody class="table-border-bottom-0">
                                <!-- Data will be loaded via AJAX -->
                            </tbody>
                        </table>
                    </div>

                    <!-- Loading spinner -->
                    <div id="loadingSpinner" class="text-center p-4" style="display: none;">
                        <div class="spinner-border text-primary" role="status">
                            <span class="visually-hidden">Loading...</span>
                        </div>
                    </div>

                    <!-- No data message -->
                    <div id="noDataMessage" class="text-center p-4" style="display: none;">
                        <p class="text-muted">No bookings found.</p>
                    </div>

                    <!-- Pagination -->
                    <div class="card-footer">
                        <div class="row align-items-center">
                            <div class="col-md-6">
                                <span id="tableInfo" class="text-muted">Showing 0 to 0 of 0 entries</span>
                            </div>
                            <div class="col-md-6">
                                <nav aria-label="Table pagination">
                                    <ul class="pagination justify-content-end mb-0" id="pagination">
                                        <!-- Pagination will be generated by JavaScript -->
                                    </ul>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <footer class="content-footer footer bg-footer-theme">
            <div class="container-xxl">
                <div
                    class="footer-container d-flex align-items-center justify-content-between py-4 flex-md-row flex-column">
                    <div class="mb-2 mb-md-0">
                        &#169;
                        <script>
                            document.write(new Date().getFullYear());
                        </script>, Mountain Management System
                    </div>
                </div>
            </div>
        </footer>

        <div class="content-backdrop fade"></div>
    </div>
@endsection

@push('scripts')
<script>
    $(document).ready(function() {
        let currentPage = 1;
        let itemsPerPage = 10;
        let searchTerm = '';
        let totalRecords = 0;
        let searchTimeout;

        loadBookings();

        $('#searchInput').on('keyup', function() {
            clearTimeout(searchTimeout);
            searchTerm = $(this).val();

            searchTimeout = setTimeout(function() {
                currentPage = 1;
                loadBookings();
            }, 500);
        });

        function loadBookings() {
            showLoading();

            $.ajax({
                url: '{{ route("bookings.getData") }}',
                type: 'GET',
                data: {
                    search: searchTerm,
                    start: (currentPage - 1) * itemsPerPage,
                    length: itemsPerPage
                },
                success: function(response) {
                    hideLoading();
                    totalRecords = response.recordsTotal;

                    if (response.data && response.data.length > 0) {
                        renderTable(response.data);
                        renderPagination();
                        updateTableInfo();
                        $('#noDataMessage').hide();
                    } else {
                        renderEmptyState();
                    }
                },
                error: function(xhr) {
                    hideLoading();
                    console.error(xhr.responseText);
                    alert('Error loading data. Please try again.');
                }
            });
        }

        function renderTable(data) {
            let html = '';

            // Hitung nomor awal untuk halaman saat ini
            // Rumus: ((Halaman saat ini - 1) * Jumlah data per halaman) + 1
            let rowNumber = (currentPage - 1) * itemsPerPage + 1;

            data.forEach(function(row) {
                const statusBadge = getStatusBadge(row.status);
                const actionButtons = getActionButtons(row);

                html += `
                    <tr>
                        <td><span class="fw-bold">${rowNumber}</span></td>
                        <td>
                            <div class="d-flex align-items-center">
                                <i class="ri-user-line text-info me-2"></i>
                                ${row.user_name}
                            </div>
                        </td>
                        <td>${row.email}</td>
                        <td>
                            <i class="ri-mountain-line text-success me-2"></i>
                            ${row.mountain_name}
                        </td>
                        <td>${row.team_size || 0} Org</td>
                        <td>${row.checkin_time || '-'}</td>
                        <td>${row.checkout_time || '-'}</td>
                        <td>${statusBadge}</td>
                        <td>${actionButtons}</td>
                    </tr>`;

                rowNumber++; // Tambah nomor urut untuk baris berikutnya
            });

            $('#bookingsTable tbody').html(html);
        }

        function getStatusBadge(status) {
            let badgeClass = '';
            let statusText = status.replace('_', ' ').toUpperCase();

            switch (status) {
                case 'active':     badgeClass = 'bg-label-warning'; break;
                case 'checked_in': badgeClass = 'bg-label-success'; break;
                case 'completed':  badgeClass = 'bg-label-primary'; break;
                case 'cancelled':  badgeClass = 'bg-label-danger';  break;
                default:           badgeClass = 'bg-label-secondary';
            }
            return `<span class="badge rounded-pill ${badgeClass}">${statusText}</span>`;
        }

        function getActionButtons(row) {
            if (row.status === 'active') {
                return `<button class="btn btn-sm btn-success" onclick="checkin(${row.id})">
                            <i class="ri-login-box-line me-1"></i> Check-in
                        </button>`;
            }
            if (row.status === 'checked_in') {
                return `<button class="btn btn-sm btn-primary" onclick="checkout(${row.id})">
                            <i class="ri-logout-box-line me-1"></i> Check-out
                        </button>`;
            }
            return `<span class="text-muted small">Selesai</span>`;
        }

        window.checkin = function(id) {
            if (!confirm('Apakah Anda yakin ingin melakukan Check-in?')) return;

            $.post(`/dashboard/bookings/${id}/checkin`, { _token: '{{ csrf_token() }}' })
                .done(function() {
                    loadBookings();
                })
                .fail(function() {
                    alert('Gagal melakukan check-in.');
                });
        };

        window.checkout = function(id) {
            if (!confirm('Apakah Anda yakin ingin melakukan Check-out?')) return;

            $.post(`/dashboard/bookings/${id}/checkout`, { _token: '{{ csrf_token() }}' })
                .done(function() {
                    loadBookings();
                })
                .fail(function() {
                    alert('Gagal melakukan check-out.');
                });
        };

        function renderPagination() {
            const totalPages = Math.ceil(totalRecords / itemsPerPage);
            let html = '';

            if (totalPages <= 1) {
                $('#pagination').empty();
                return;
            }

            html += `
                <li class="page-item ${currentPage === 1 ? 'disabled' : ''}">
                    <a class="page-link" href="javascript:void(0);" onclick="changePage(${currentPage - 1})">
                        <i class="ri-arrow-left-s-line"></i>
                    </a>
                </li>`;

            for (let i = 1; i <= totalPages; i++) {
                html += `
                    <li class="page-item ${i === currentPage ? 'active' : ''}">
                        <a class="page-link" href="javascript:void(0);" onclick="changePage(${i})">${i}</a>
                    </li>`;
            }

            html += `
                <li class="page-item ${currentPage === totalPages ? 'disabled' : ''}">
                    <a class="page-link" href="javascript:void(0);" onclick="changePage(${currentPage + 1})">
                        <i class="ri-arrow-right-s-line"></i>
                    </a>
                </li>`;

            $('#pagination').html(html);
        }

        window.changePage = function(page) {
            const totalPages = Math.ceil(totalRecords / itemsPerPage);
            if (page < 1 || page > totalPages) return;

            currentPage = page;
            loadBookings();
        };

        function updateTableInfo() {
            const start = (currentPage - 1) * itemsPerPage + 1;
            const end = Math.min(currentPage * itemsPerPage, totalRecords);
            $('#tableInfo').text(`Showing ${start} to ${end} of ${totalRecords} entries`);
        }

        function renderEmptyState() {
            $('#bookingsTable tbody').empty();
            $('#pagination').empty();
            $('#tableInfo').text('Showing 0 to 0 of 0 entries');
            $('#noDataMessage').show();
        }

        function showLoading() {
            $('#loadingSpinner').show();
            $('#bookingsTable tbody').css('opacity', '0.5');
            $('#noDataMessage').hide();
        }

        function hideLoading() {
            $('#loadingSpinner').hide();
            $('#bookingsTable tbody').css('opacity', '1');
        }
    });
</script>
@endpush
